version: '3.8'

services:
  usersdb:
    image: mongo:5.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_USERNAME: myUser
      MONGO_INITDB_PASSWORD: myPass
      MONGO_INITDB_DATABASE: usersdb
    ports:
      - 27018:27017
    volumes:
      - ./config/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - usersdb-dev-volume:/adapters/db
    command: mongod --bind_ip_all

volumes:
  usersdb-dev-volume:
